Jedox.wss.app.dynJSRegistry = {
	formatCells : [ "Format.js", [ "dialog" ], "formatCells", false, false,
			"ui/app/base" ],
	chart : [ "insertChart.js", [ "dialog", "chart" ], "openChartDialog",
			false, false, "ui/app/base" ],
	editChart : [ "editChart.js", [ "dialog", "chart" ], "editChartDialog",
			false, false, "ui/app/base" ],
	editChartType : [ "editChartType.js", [ "dialog", "chart" ],
			"editChartTypeDialog", false, false, "ui/app/base" ],
	editSourceData : [ "editSourceData.js", [ "dialog", "chart" ],
			"editSourceDataDialog", false, false, "ui/app/base" ],
	editMacro : [ "editMacro.js", [ "dialog" ], "openEditMacro", false, false,
			"ui/app/base" ],
	insertMacro : [ "insertMacro.js", [ "dialog" ], "openInsertMacro", false,
			false, "ui/app/base" ],
	find : [ "find.js", [ "dialog" ], "openFindDialog", false, false, "ui/app/base" ],
	open : [ "open.js", [ "dialog" ], "openOpenDialog", false, false, "ui/app/base" ],
	insertFunction : [ "InsertFunction.js", [ "dialog" ],
			"openInsertFunctionDialog", false, false, "ui/app/base" ],
	conditionalFormatting : [ "ConditionalFormatting.js", [ "dialog" ],
			"openConditionalFormatting", false, false, "ui/app/base" ],
	manageConditionalFormatting : [ "manageConditionalFmt.js", [ "dialog" ],
			"manageConditionalFormatting", false, false, "ui/app/base" ],
	formatColRow : [ "formatColRow.js", [ "dialog" ], "openFormatColRow",
			false, false, "ui/app/base" ],
	importFile : [ "import.js", [ "dialog" ], "openImportDialog", false, false,
			"ui/app/base" ],
	microChart : [ "microchart.js", [ "dialog", "chart" ], "MicroChart", false,
			false, "ui/app/base" ],
	insertDynarange : [ "insertDynarange.js", [ "dialog" ],
			"openDynarangeEditor", false, false, "ui/app/base" ],
	sheetMoveCopy : [ "sheetMoveCopy.js", [ "dialog" ], "openSheetMoveCopy",
			false, false, "ui/app/base" ],
	nameManager : [ "nameManager.js", [ "dialog" ], "openNameManager", false,
			false, "ui/app/base" ],
	newName : [ "newName.js", [ "dialog" ], "openNewName", false, false, "ui/app/base" ],
	selectRange : [ "selectRange.js", [ "dialog" ], "openSelectRangeDialog",
			false, false, "ui/app/base" ],
	renameSheet : [ "renameSheet.js", [ "dialog" ], "openRenameSheet", false,
			false, "ui/app/base" ],
	pageSetup : [ "pageSetup.js", [ "dialog" ], "openPageSetup", false, false,
			"ui/app/base" ],
	customHeaderFooter : [ "customHeaderFooter.js", [ "dialog" ],
			"openCustomHeaderFooter", false, false, "ui/app/base" ],
	arrangeWindows : [ "arrangeWindows.js", [ "dialog" ], "openArrangeWindows",
			false, false, "ui/app/base" ],
	unhideWindow : [ "unhideWindow.js", [ "dialog" ], "openUnhideDialog",
			false, false, "ui/app/base" ],
	modeller : [ "modeller.js", [ "palo" ], "openModellerDialog", false, false,
			"ui/common/base" ],
	cubeWizard : [ "cubewizard.js", [ "palo" ], "CubeWizard", false, false,
			"ui/common/base" ],
	paloWizard : [ "palowizard.js", [ "palo" ], "openPaloWizard", false, false,
			"ui/common/base" ],
	subsetEditor : [ "subseteditor.js", [ "palo" ], "openSubsetEditor", false,
			false, "ui/common/base" ],
	ruleEditor : [ "ruleeditor.js", [ "palo" ], "ruleEditor", false, false,
			"ui/common/base" ],
	chooseElement : [ "chooseelement.js", [ "palo" ], "ChooseElement", false,
			false, "ui/common/base" ],
	pasteView : [ "pasteview.js", [ "palo" ], "PasteView", false, false, "ui/app/base" ],
	selectElements : [ "selectelements.js", [ "palo" ], "SelectElements",
			false, false, "ui/app/base" ],
	pasteDataFunctions : [ "pastefuncs.js", [ "palo" ], "PasteDataFunctions",
			false, false, "ui/app/base" ],
	paloImport : [ "paloimport.js", [ "palo" ], "openPaloImport", false, false,
			"ui/app/base" ],
	openHL : [ "insertHyperlink.js", [ "dialog" ], "openHL", false, false,
			"ui/app/base" ],
	hlVarList : [ "hl_varList.js", [ "dialog" ], "hlVarList", false, false,
			"ui/app/base" ],
	funcArgs : [ "funcArgs.js", [ "dialog" ], "funcArgs", false, false, "ui/app/base" ],
	formatControl : [ "formatControl.js", [ "dialog" ], "formatControl", false,
			false, "ui/app/base" ],
	pasteSpecial : [ "pasteSpecial.js", [ "dialog" ], "openPasteSpecial",
			false, false, "ui/app/base" ],
	autoRefreshStart : [ "autoRefresh.js", [ "dialog" ], "autoRefreshStart",
			false, false, "ui/app/base" ],
	quickPublish : [ "quickPublish.js", [ "dialog" ], "quickPublish", false,
			false, "ui/app/base" ],
	recover : [ "recover.js", [ "dialog" ], "openRecoverDialog", false, false,
			"ui/app/base" ],
	goTo : [ "goTo.js", [ "dialog" ], "openGoTo", false, false, "ui/app/base" ],
	formatFont : [ "font.js", [ "dialog", "format" ], "font", false, false,
			"ui/app/base" ],
	formatNumber : [ "number.js", [ "dialog", "format" ], "number", false,
			false, "ui/app/base" ],
	formatAlignment : [ "alignment.js", [ "dialog", "format" ], "alignment",
			false, false, "ui/app/base" ],
	formatBorder : [ "border.js", [ "dialog", "format" ], "border", false,
			false, "ui/app/base" ],
	formatFill : [ "fill.js", [ "dialog", "format" ], "fill", false, false,
			"ui/app/base" ],
	formatProtection : [ "protection.js", [ "dialog", "format" ], "protection",
			false, false, "ui/app/base" ]
};