<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xsl:output version="1.0" method="html" indent="no" encoding="UTF-8"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<table width="{/worksheet/grid/@width}" cellpadding="0" cellspacing="0">
						<tbody>
							<xsl:for-each select="worksheet">
								<xsl:for-each select="grid">
									<xsl:for-each select="rows">
										<xsl:for-each select="row">
											<tr style="height:{@height}; ">
													<xsl:for-each select="cells">
																	<xsl:for-each select="cell">
																		<td colspan="{@colspan}" rowspan="{@rowspan}" style="vertical-align:top; background-color:{@background-color}; color:{@color}; font-family:{@font-family}; font-size:{@font-size}; font-style:{@font-style}; font-weight:{@font-weight}; height:{../../@height}; text-align:{@text-align}; text-decoration:{@text-decoration}; width:{@width}; text-indent:{@text-indent}; border-bottom:{@border-bottom}; border-left:{@border-left}; border-top:{@border-top}; border-right:{@border-right}; background-image:url({@background-image}); white-space:{@white-space};">
																			<div style="padding-left:2px;overflow: hidden; height:{../../@height};">
																				<xsl:for-each select="value">
																					<xsl:apply-templates/>
																				</xsl:for-each>
																			</div>
																		</td>
																	</xsl:for-each>
													</xsl:for-each>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<xsl:for-each select="worksheet">
                        <xsl:for-each select="grid">
                            <xsl:for-each select="charts">
                                <xsl:for-each select="chart">
                                    <img style="left:{@left}; position:absolute; top:{@top}; width:{@width}; height:{@height};">
                                        <xsl:attribute name="src">
                                            <xsl:value-of select="translate(string(@src), '&#x5c;', '/')" />
                                        </xsl:attribute>
                                        <xsl:attribute name="alt" />
                                    </img>
                                </xsl:for-each>
                            </xsl:for-each>
                        </xsl:for-each>
                    </xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
