<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xsl:output version="1.0" method="html" indent="no" encoding="UTF-8"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<table width="100%">
					<tbody>
						<tr>
							<td align="center" height="500">
								<xsl:for-each select="$XML">
									<xsl:for-each select="message">
										<xsl:for-each select="img">
											<img style="height:{@h}; max-height:{@w}; ">
												<xsl:attribute name="src">
													<xsl:if test="substring(string(@path), 2, 1) = ':'">
														<xsl:text>file:///</xsl:text>
													</xsl:if>
													<xsl:value-of select="translate(string(@path), '&#x5c;', '/')"/>
												</xsl:attribute>
												<xsl:attribute name="alt"/>
											</img>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<br/>
								<br/>
								<xsl:for-each select="$XML">
									<xsl:for-each select="message">
										<xsl:for-each select="text">
											<span style="font-weight:bold; ">
												<xsl:apply-templates/>
											</span>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
					</tbody>
				</table>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
