// This class is generated. Do NOT modify it, or
// add it to source control.

package mondrian.resource;

import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import org.eigenbase.resgen.*;

/**
 * This class was generated by class org.eigenbase.resgen.ResourceGen from
 * D:/opensource
 * /projects/report/pentaho/mondrian-3.3.0.14703/mondrian-3.3.0.14703
 * /mondrian-3.3.0.14703-src/mondrian-3.3.0.14703/src/main/mondrian/resource/
 * MondrianResource.xml on Sun Apr 22 18:24:17 CST 2012. It contains a list of
 * messages, and methods to retrieve and format those messages.
 */

public class MondrianResource_de extends MondrianResource {
	public MondrianResource_de() throws IOException {
	}
}

// End MondrianResource_de.java
